### ISSUE TITLE
Dynamic increase item and remove support

### ISSUE THREAD

**Issue by SarcoZ** [alicommit-malp/roundrobin#1]
Can support dynamic increase item and remove?

**Comment by alicommit-malp** [comment]
hi :) 
2 questions: 
1- regarding the remove, you mean remove from the RoundRobinList ?
2- regarding the dynamic increase, can give an example of your input and desired  output ? 

Thanks

**Comment by vertigosoft** [comment]
the round robin start from the beginning again after an application restart.  
Will there be support for continuation for such scenario

**Comment by alicommit-malp** [comment]
closing this because of no answer
