### ISSUE TITLE
Suggestions regarding thread safe implementation

### ISSUE THREAD

**Issue by fr4gles** [alicommit-malp/roundrobin#2]
Hello,

1. There are 7 different locks, each for one single method: https://github.com/alicommit-malp/roundrobin/blob/master/src/RoundRobin/RoundRobinList.cs
```
        private readonly object _lockNext = new object();
        private readonly object _lockNexts = new object();
        private readonly object _lockIncreaseWeight = new object();
        private readonly object _lockDecreaseWeight = new object();
        private readonly object _lockResetAllWeights = new object();
        private readonly object _lockReset = new object();
        private readonly object _lockResetWeight = new object();
```
to synchronize access to one instance of `_linkedList`.

It's a problem because anyone can invoke `ResetAllWeights` / `ResetWeight` / `DecreaseWeight` (or other methods) each on a different thread with different values and will face a race condition problem.

According to MS documentation https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement#guidelines my suggestion would be to **use singe lock object to access single resource**, in this case to limit access to `_linkedList`. Single lock object will do the trick and implementation will become truly thread safe.

2. I would also suggest to improve tests by using `Task.Run` instead of `Task.Factory.StartNew` which is preffered way to start new Task and also because of default `DenyChildAttach` option in `Task.Run`.
https://devblogs.microsoft.com/pfxteam/task-run-vs-task-factory-startnew/ 
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-prevent-a-child-task-from-attaching-to-its-parent

**Comment by alicommit-malp** [comment]
Thank you for your suggestions :) 
https://www.nuget.org/packages/RoundRobin/2.0.1
https://github.com/alicommit-malp/roundrobin/releases/tag/v2.0.1
