### ISSUE TITLE
continuation after an application restart

### ISSUE THREAD

**Issue by vertigosoft** [alicommit-malp/roundrobin#3]
the round robin start from the beginning again after an application restart.
Will there be support for continuation from the last item before application restart

**Comment by alicommit-malp** [comment]
This library is generic therefore you can have any type including tcp connections for instance therefore the next time the application will restart the list of elements may change or not available but for supporting what you have asked i added ResetTo method to the library 

        [Test]
        public void RoundRobin_StartTo()
        {
            var rb = new RoundRobinList<int>(_data);
            rb.ResetTo(4);

            var result = new List<int>();
            for (var i = 0; i < 10; i++)
            {
                result.Add(rb.Next());
            }

            result.ForEach(z => { TestContext.Write($"{z},"); });

            var mustBe = new List<int>()
            {
                5, 1, 2, 3, 4, 5, 1, 2, 3, 4
            };

            Assert.AreEqual(result, mustBe);
        }

so you can according to your application persist the last accessed item and when the application restarted retrieve it and use the ResetTo to start the round robin from that point 

nuget version 2.1.0 with this feature has uploaded https://www.nuget.org/packages/RoundRobin/2.1.0

happy coding :)
